### ISSUE TITLE
cheats

### ISSUE THREAD

**Issue by larsonbraxton40** [Cattn/gba-host#3]
do cheats not work for gba or is it just certain games have working cheats

**Comment by JavaScythe** [comment]
only certain games are supported.
if you want, you can provide cheats and we'll add them.

**Comment by larsonbraxton40** [comment]
ok I was just wondering because I couldn't find any for pokemon red

**Comment by JavaScythe** [comment]
https://www.pokemoncoders.com/pokemon-red-cheats/

**Comment by larsonbraxton40** [comment]
I have tried them but ill try again

**Comment by JavaScythe** [comment]
oh
then it's a problem with emulatorjs

**Comment by larsonbraxton40** [comment]
I dont know much about emulatorjs but do you know of any fixes or can you bring it up to some one to fix?

**Comment by JavaScythe** [comment]
i also know very little about emulatorjs but I would try leaving a comment on their github https://github.com/EmulatorJS/EmulatorJS

**Comment by Cattn** [comment]
Yeah cheat codes are kinda funky leave a issue on their github for best result/more info

**Comment by larsonbraxton40** [comment]
this probably just made me look stupid but here's the link just incase you wanna see any replies https://github.com/EmulatorJS/EmulatorJS/issues/452

**Comment by Cattn** [comment]
Thanks for leaving reply there

**Comment by JavaScythe** [comment]
bruh
