### ISSUE TITLE
Problems deploying

### ISSUE THREAD

**Issue by GamerGoat112** [Cattn/gba-host#4]
It fails to deploy the pages. idk how to fix it

**Comment by Nailington** [comment]
Could u send me a picture of the part of the logs where it fails

**Comment by Nailington** [comment]
Because I have noticed this behavior on our end too, but could be unrelated

**Comment by Nailington** [comment]
And doesn't always happen

**Comment by Cattn** [comment]
https://github.com/GamerGoat112/gba-host/actions/runs/4050129170/jobs/6967213853

**Comment by Cattn** [comment]
Yes this is an issue, It's really weird Ima look into it

**Comment by Cattn** [comment]
![image](https://user-images.githubusercontent.com/69491394/215650338-455e1896-61fd-46e1-8469-f6e9857b35f0.png)
@GamerGoat112 could you try swapping the deployment to this?

**Comment by Nailington** [comment]
I actually havent seen that error before..... Try @Cattn's method :)

**Comment by GamerGoat112** [comment]
K I did that and it worked.

**Comment by Cattn** [comment]
Alright perfect I'll update the guide later to reflect that

**Comment by GamerGoat112** [comment]
How do I set it as my custom host?

**Comment by GamerGoat112** [comment]
It says failed to load content

**Comment by Cattn** [comment]
What's your link?

**Comment by Cattn** [comment]
I found it, for Custom host:

Please toggle ON, then OFF Custom host.

Then after that, paste in this link: https://gamergoat112.github.io/gba-host/ (Including the / at the end!) And then toggle the switch ON
